### ISSUE TITLE
Add a Middleware Component

### ISSUE THREAD

**Issue by dolfelt** [sparkphp/spark#10]
We need to have some sort of middleware. @shadowhand @ameech

**Comment by ameech** [comment]
I did a little work on this and I'm not sure it's even 100% of the direction we want to go, but wanted to get the ball rolling: #11

**Comment by shadowhand** [comment]
What would the middleware do?

**Comment by ameech** [comment]
If you're talking about mine, it does nothing. It's just an idea of how it would work.

**Comment by shadowhand** [comment]
No, I just mean in general, what are the expected use cases for middlware?

**Comment by dolfelt** [comment]
I was thinking auth specifically. @shadowhand

**Comment by elazar** [comment]
Good examples of use cases for middleware: http://stackphp.com/middlewares/

**Comment by dolfelt** [comment]
Definitely! Thanks @elazar.

**Comment by shadowhand** [comment]
@elazar @dolfelt authentication is not middleware, it's business logic. [Radar docs](https://github.com/radarphp/Radar.Project/blob/1.x/docs/middleware.md) talk about this.

**Comment by dolfelt** [comment]
@shadowhand So where would you put it? In the input manipulation? Where would it go in the flow?

**Comment by shadowhand** [comment]
@dolfelt auth is business logic, so it would go in the domain. Probably as a trait, or shared in some other way.

**Comment by dolfelt** [comment]
Blarg! A trait? I could see extending an `AuthDomain` class.

**Comment by shadowhand** [comment]
What happens if you need both auth and sessions? Traits work for composition.

**Comment by elazar** [comment]
I can see the argument being made for authentication being handled in the domain. That said, I think I'd prefer to favor composition over traits in this instance. That is, have a class for handling authentication and have an instance of that class be injected into any action class instance that requires authentication.

**Comment by shadowhand** [comment]
Works better for the injector, so I'm fine with that.

**Comment by elazar** [comment]
I'm admittedly a bit confused as to exactly what intended use cases for middleware might be in Radar, judging from the [Radar docs](https://github.com/radarphp/Radar.Project/blob/1.x/docs/middleware.md#middleware-and-domain-activity) that @shadowhand linked earlier and [what StackPHP uses them for](http://stackphp.com/middlewares/). @pmjones any chance you could provide some clarification?

**Comment by dolfelt** [comment]
I can see them being very useful for modifying HTTP attributes, such as CORS headers for an API.

**Comment by elazar** [comment]
@dolfelt Those headers could vary per action, though. Unless you wanted to use the same headers across all resources, though at that point you could just as easily handle that in web server configuration.

**Comment by pmjones** [comment]
> I'm admittedly a bit confused as to exactly what intended use cases for middleware might be in Radar, 

I lack imagination here. So much of what others use middleware for is misapplied, to me. (And with routes, too.) I can see cases for modifying the request inbound, and modifying the request outbound, but that's about it.  For example, if the incoming content-type is application/json, a middleware piece could decode the request body into readable parameters so various Actions don't have to do that over and over and over.  But even that could be handled by a generic Input object fed to the Action. For outbound stuff, it's the same thing, since the Responder has full control over the response, and it can (e.g.) encrypt cookies if needed.

The main thing in Radar for middleware is to get the various core pieces out where they can be replaced: the routing, the core action, and the sending. However, just because I lack imagination does not mean it might not come in useful; I *can* imagine other people having more imagination than me.

That's a vague and long-winded answer; please let me know if it helps or not.

**Comment by dolfelt** [comment]
Definitely helps. Thanks @pmjones!

**Comment by shadowhand** [comment]
As food for thought, let's remember this image (from StackPHP):

![http stack](http://stackphp.com/img/onion.png)

Now, I disagree that session/auth are part of the "onion", but in the "stack" pattern the request gets passed in and the response comes back. Each inner layer uses the (possibly modified) request and gets back the (possibly modified) response.

This is not necessarily right or wrong, just a clear visual of the pattern:

```php
$response = $middle($request, $response, $next);
```

**Comment by elazar** [comment]
I agree with Paul's views regarding the role of middleware: they should be strictly for modifying the request or response without interacting with anything domain-specific (e.g. data stores). Request body decoding and response body encryption are good examples of those. Authentication and other concerns that do require accessing data outside of the request or response should be part of the domain.

**Comment by shadowhand** [comment]
@elazar totally agree, as a visual person I just like the StackPHP diagram of how the middle/next pattern works. Not at all saying we should adopt it for session/auth.

**Comment by elazar** [comment]
Was this resolved by the addition of [`Spark\Adr\MiddlewareInterface`](https://github.com/sparkphp/adr/blob/master/src/MiddlewareInterface.php) ?

**Comment by shadowhand** [comment]
It was. Thanks!
