### ISSUE TITLE
Add .gitattributes to exclude unneeded files for packages

### ISSUE THREAD

**Issue by elazar** [sparkphp/Spark#15]
See the "Making your Composer project lighter" section of [this article](http://www.sitepoint.com/mastering-composer-tips-tricks/). Create a `.gitattributes` file in the root of the repo with entries for files like those under `tests`, `.travis.yml`, and others not needed by end users.

**Comment by dolfelt** [comment]
Thanks for the suggestion @elazar! :+1:
