### ISSUE TITLE
Consider removing APP_PATH

### ISSUE THREAD

**Issue by elazar** [sparkphp/Spark#16]
`APP_PATH` is [presently used](https://github.com/sparkphp/Spark/search?utf8=%E2%9C%93&q=APP_PATH) as a constant defined in the global namespace. If it is undefined, the `Application` class will produce an error like this: `Notice: Use of undefined constant APP_PATH - assumed 'APP_PATH'`.

It would make more sense to make this a configuration setting, perhaps stored in the `Injector` instance passed to `Application::boot()` or as a separate parameter to it, because it's a value that can vary from environment to environment: it may take on one value in my local development environment, another on a staging server, and yet another on a production server.

**Comment by dolfelt** [comment]
@elazar I definitely agree. I think this should probably be stored in configuration somewhere, or as a parameter in the application itself. Probably not directly in the injector though.

**Comment by elazar** [comment]
`APP_PATH` is currently only used in `ExceptionHandler`, which I think could do without it, and in `Application` for configuration, which I think can be removed in favor of having projects use it directly. As part of this, we could move the `josegonzalez\dotenv` package from `require` to `suggest` in `composer.json`.
