### ISSUE TITLE
Create a public room on gitter for SparkPHP

### ISSUE THREAD

**Issue by aghos7** [sparkphp/spark#20]
I was creating a simple app in SparkPHP last night and had a few questions.  I could ask them here, but I thought you may have a public community gitter room/channel.  I went to https://gitter.im/sparkphp/ hoping to find a public room/channel; alas there was not.

Thoughts on creating one? (or an IRC channel)
I'd prefer slack, but I know how @shadowhand likes gitter :smile: 
@shadowhand @dolfelt

**Comment by elazar** [comment]
Feel free to file support issues if you have questions. Documentation is forthcoming and hopefully imminent. At the moment, however, we don't have sufficient people or time to staff a real time support channel.
