### ISSUE TITLE
Change payload implementations

### ISSUE THREAD

**Issue by elazar** [sparkphp/spark#26]
We've been discussing moving away from `aura/payload`, so I thought I'd create an issue to try to centralize discussion points. The main reason I've seen has been to reduce complexity: the [`AbstractPayload`](https://github.com/auraphp/Aura.Payload/blob/3.x/src/AbstractPayload.php) and [`Payload`](https://github.com/auraphp/Aura.Payload/blob/3.x/src/Payload.php) have a lot of stuff that we don't necessarily need or use.

Most suggestions for an alternative have ranged from a plain `array` to a simplified payload class, possibly implementing [`ArrayAccess`](http://php.net/manual/en/class.arrayaccess.php). Not sure there are any third-party implementations out there outside of Aura that would be of interest.

Thoughts @ameech @dolfelt @shadowhand ?

**Comment by shadowhand** [comment]
I'd like to use a class so that it can be type hinted and injected into the domain via the constructor. I think the minimum interface would be:

```php
interface PayloadInterface
{
    public function withStatus(int $status);
    public function getStatus();
    public function withOutput(array $output);
    public function getOutput();
    public function withMessages(array $messages);
    public function getMessages();
}
```

This would be the complete (immutable) interface and there would be no default status codes provided.

**Comment by elazar** [comment]
That seems sufficient. Would this be worth putting in its own repo? Or should it be bundled with sparkphp/Spark? Or sparkphp/adr?

**Comment by shadowhand** [comment]
I think it makes sense to have the interface in sparkphp/adr and the implementation in sparkphp/spark.

**Comment by elazar** [comment]
Makes sense to me. Any objections to proceeding with this approach @dolfelt @ameech?

**Comment by dolfelt** [comment]
@shadowhand @elazar I think this is a great approach. My initial reaction says we should include in the interface some way to store a code/identifier/etc. but maybe the `status` is enough for that.

Also, for all these changes, what version do we want to bump to? `v0.4.0`?

**Comment by shadowhand** [comment]
Yes to 0.4.0. I think the status should be a constant (not a HTTP status).

**Comment by shadowhand** [comment]
This is done.
