### ISSUE TITLE
Responder chaining support

### ISSUE THREAD

**Issue by elazar** [sparkphp/spark#27]
Just posting this to start related discussion and see if we should pursue this idea or not.

This will probably depend on #26 since the affected code deals with the payload.

The crux of the idea is supporting call chains for responders as we currently do for actions with the [`ActionHandler`](https://github.com/sparkphp/Spark/blob/master/src/Handler/ActionHandler.php) implementation. The purpose of this would be to at minimum provide for separation of protocol (e.g. HTTP, CLI) and payload format (e.g. JSON, HTML) using composition rather than inheritance, though it likely has other potential applications.

Not sure if the result of this issue should go in this repo or in [`sparkphp/adr`](https://github.com/sparkphp/adr), which contains [`ResponderInterface`](https://github.com/sparkphp/adr/blob/master/src/ResponderInterface.php). Probably this repo, since it includes the action implementation that [supports chaining](https://github.com/sparkphp/Spark/blob/master/src/Handler/ActionHandler.php), where [`sparkphp/adr`](https://github.com/sparkphp/adr) only implements a [basic action handler](https://github.com/sparkphp/adr/blob/master/src/ActionHandler.php) (though admittedly one that I'm not sure we're actually using at this point, since we're [now using Arbiter in this repo](https://github.com/sparkphp/Spark/blob/9d26e5d22ccc73cecab6251891d38858b36edf49/src/Handler/ActionHandler.php#L5)).

This change would involve either a new interface similar to [`ResponderInterface`](https://github.com/sparkphp/adr/blob/master/src/ResponderInterface.php) or a change to that interface. The  `__invoke()` implementation would take an additional optional parameter, `callable $next`, that represents the next responder in the chain to execute, as `ActionHandler->__invoke()` does. It's possible it could use [Relay](https://github.com/relayphp/Relay.Relay) to implement the callback chain, as the current action implementation does.

This change would likely also involve refactoring [`Router`](https://github.com/sparkphp/Spark/blob/master/src/Router.php) to support multiple responders per action, as multiple middlewares are currently supported at the application level for the action implementation.

Thoughts @ameech @dolfelt @shadowhand ?

**Comment by dolfelt** [comment]
@elazar I think there are definite improvements that can be made to the `Responder

**Comment by elazar** [comment]
@dolfelt The issue with inheritance is we're trying to combine multiple disparate behaviors, i.e. those related to protocol and those related to payload format, so we can mix and match as needed, stay DRY, and maintain separation of concerns. The only means of accomplishing this with "inheritance" that I can see is using [traits](http://php.net/manual/en/language.oop5.traits.php), where composition seems a more intuitive fit to solve the problem. All that said, I'd be interested to hear how you think the current responder implementation could be improved.

**Comment by shadowhand** [comment]
I think traits might be the perfect answer to this, because it would allow having traits to define specific HTTP statuses and body handling separately. For instance, having a `HttpStatus400` trait and a `HttpBodyJson` could easily be combined into a single class.

**Comment by elazar** [comment]
@shadowhand Looks like this was resolved in 0ce168c547a1d801d0227c58767a9b15d77b24de?

**Comment by shadowhand** [comment]
By #33
