### ISSUE TITLE
What are you using for your DAL?

### ISSUE THREAD

**Issue by cballou** [sparkphp/spark#34]
Many components are missing from the framework. Did you custom roll your own data access layer or are you using something available from Packagist? Curious.

**Comment by elazar** [comment]
The purpose of Stack is really to provide a relatively minimal ADR implementation, not to be a full-stack framework, so a DAL is intentionally excluded. That said, we've generally tended toward simply using a PDO extension like FluentPDO or Aura.Sql in our Spark projects.

**Comment by shadowhand** [comment]
@cballou from our perspective, very little is missing at this point. Everything that is "missing" in terms of a full-feature framework is domain features, which we intentionally do not provide.

**Comment by cballou** [comment]
Bad choice of words on "missing". I should've said something more to the effect of the documentation doesn't readily hint at any conventions or best practices as they generally tend to be a good way to increase adoption rates.

**Comment by mvanhorne** [comment]
@shadowhand @dolfelt @ameech Sounds like a solid suggestion

**Comment by ameech** [comment]
We'll be putting together documentation soon I would think, it was taking us awhile to get everything locked down.
