### ISSUE TITLE
Feature proposal: Providers

### ISSUE THREAD

**Issue by elazar** [sparkphp/spark#35]
I think we should consider adopting a bit more structure around applying configuration to the Auryn injector.

Silex has a concept of [providers](http://silex.sensiolabs.org/doc/providers.html#service-providers), which handle applying appropriate dependency injector configuration to integrate specific libraries.

An equivalent implementation in Spark could look something like this:

```php
// src/Provider.php
interface Provider
{
    public function configure(\Auryn\Injector $injector);
}

// src/CompositeProvider.php
class CompositeProvider
{
    protected $providers;

    public function __construct(array $providers)
    {
        $this->providers = array_filter(
            $providers,
            function ($provider) {
                return $provider instanceof ProviderInterface;
            }
        );
    }

    public function configure(\Auryn\Injector $injector)
    {
        foreach ($this->providers as $provider) {
            $provider->configure($injector);
        }
    }
}

// web/index.php
$injector = new \Auryn\Injector;
$app = \Spark\Application::boot($injector);
$providers = new CompositeProvider([
    // ...
]);
$providers->configure($injector);
```

It may be possible to replace some of the [default dependency configuration in `\Spark\Application`](https://github.com/sparkphp/spark/blob/b2a9b32f461ab39f83089b9eade46f8a37e70156/src/Application.php#L26-L52) with this. Here's an example:

```php
class ZendDiactorosProvider implements ProviderInterface
{
    public function configure(\Auryn\Injector $injector)
    {
        $injector->alias(
            'Psr\Http\Message\ResponseInterface',
            'Zend\Diactoros\Response'
        );

        $injector->delegate(
            'Psr\Http\Message\ServerRequestInterface',
            'Zend\Diactoros\ServerRequestFactory::fromGlobals'
        );
    }
}
```

One thing that would need to be discussed is the best way to get application-level configuration into these, maybe as a second `array $config` parameter to `configure()` or some such.

**Comment by shadowhand** [comment]
I don't love the name "provider" because it implies "service provider" which Auryn is not. The idea is solid though.

**Comment by elazar** [comment]
Fair enough @shadowhand. I'm certainly open to other suggestions for more descriptive terminology.

**Comment by shadowhand** [comment]
What if we just changed the signature for `Application::boot` to:

```php
function boot($injector, array $modifiers = []) { ... }
```

Instead of having a separate `CompositeProvider` ?

**Comment by elazar** [comment]
Yeah, that approach would work.

**Comment by elazar** [comment]
Looking at this closer, I've never particularly cared for the static `boot()` method. I'd honestly rather we either extend Auryn or add a separate class that takes in the injector and array of "modifiers," or whatever we want to call them, to handle applying common sets of configuration to the injector. This new class could have a default set of modifiers that include the ones currently included in `boot()`.

Thoughts?

**Comment by shadowhand** [comment]
Agreed, I was thinking something similar yesterday when working on a project. I'd like to see a default `Configuration` or similar class:

```php
interface Configuration
{
    public function apply(Injector $injector);
}
```

**Comment by elazar** [comment]
:+1: Works for me. I'll go ahead and start on a PR for this.
