### ISSUE TITLE
Support container interoperation?

### ISSUE THREAD

**Issue by elazar** [sparkphp/spark#39]
See related discussion on rdlowrey/auryn#77, in particular this quote by @shadowhand:

> I think there is potentially a tiny bit of convenience in having a common interface that allows people to replace the injector that is used by a framework, _even though the framework does not **need** to depend on a specific injector_, because pushing all injector configuration onto the user is not convenient for anyone.

I agree with this. Even if FIG never reaches a resolution on the container versus service locator argument, I still think there's potential value in supporting [container inoperation](https://github.com/container-interop/container-interop/blob/master/docs/ContainerInterface.md). More specifically, it would allow Spark users the choice of which container they use, even if we as Spark developers tend to choose Auryn in particular.

See also my argument for Auryn interoperation support and how an implementation could work in rdlowrey/auryn#127. The only thing I'm unsure of is specific implementation details for `ContainerInterface->has()`, which is open for discussion.

Thoughts?

**Comment by shadowhand** [comment]
I don't see this being possible right now and I don't think there is a terribly strong reason for it. The best thing we could do is go "full resolver" and only pass `ResolverInterface` inside of the app. I'm not entirely sure how that would work when it comes to the couple of `share()` calls we make inside the app for the resolved route, etc.
