### ISSUE TITLE
Application dependency injection

### ISSUE THREAD

**Issue by elazar** [sparkphp/spark#42]
[`Application`](https://github.com/sparkphp/spark/blob/master/src/Application.php) is currently using the Auryn `Injector` instance as a service locator, which is specifically [recommended against](https://github.com/rdlowrey/Auryn#how-it-works) in Auryn documentation:

> auryn **is NOT** a Service Locator. DO NOT turn it into one by passing the injector into your application classes.

Here are instances of this issue:
* `__construct()` does the very thing described above: it [takes the injector](https://github.com/sparkphp/spark/blob/368430e25517f740d52a55a799f83d9ea0a8e39d/src/Application.php#L31) as a parameter.
* `run()` falls back to the container to generate default values for the [request](https://github.com/sparkphp/spark/blob/368430e25517f740d52a55a799f83d9ea0a8e39d/src/Application.php#L65-L67) and [response](https://github.com/sparkphp/spark/blob/368430e25517f740d52a55a799f83d9ea0a8e39d/src/Application.php#L68-L70) objects.
* `handle()` pulls the [resolver](https://github.com/sparkphp/spark/blob/368430e25517f740d52a55a799f83d9ea0a8e39d/src/Application.php#L89) and [middleware dispatcher](https://github.com/sparkphp/spark/blob/368430e25517f740d52a55a799f83d9ea0a8e39d/src/Application.php#L90) out of the container.

Here are some ideas I have on addressing this:

1. Rather than having the `addRoutes()` method to expose the addition of routes via callbacks, just expect the router to be pre-configured. While it requires slightly more code, the router configuration can be cleanly encapsulated in a [configuration](https://github.com/sparkphp/spark/blob/master/src/Configuration/ConfigurationInterface.php).
2. Rather than having `run()` accept the request and response objects, have the constructor accept them. This allows Auryn to handle injecting them and removes the need for calls to the injector inside of `run()`. At that point, the same parameters can be removed from `handle()`.
3. Create a new class, `CallbackCollection` or some such, that implements type checking and iteration of a set of callbacks, and have middleware specs be passed in as an instance of that.

Side note: the `$catch` parameter to `run()` can probably be removed, as it doesn't appear to be used.

This will move all configuration to the injector such that the bootstrap should become relatively trivial:

```php
require __DIR__ . '/../vendor/autoload.php';
$injector = new \Auryn\Injector;
$configuration = new \My\DefaultConfigurationSet;
$configuration->apply($injector);
$app = $injector->make('\\Spark\\Application');
$app->run();
```

Thoughts @shadowhand @dolfelt @ameech ?

**Comment by shadowhand** [comment]
Works for me!

**Comment by ameech** [comment]
:+1: Makes sense!
