### ISSUE TITLE
Remove JsonContentHandler in favor of JsonDecoder

### ISSUE THREAD

**Issue by elazar** [sparkphp/spark#55]
Relay provides a [`JsonDecoder`](https://github.com/relayphp/Relay.Middleware/tree/b4e09bd21e426732e009d91eb808ef5929af6633#jsondecoder) middleware for automatic decoding of JSON request bodies, which has functional overlap with our existing [`JsonContentHandler`](https://github.com/sparkphp/spark/blob/master/src/Handler/JsonContentHandler.php) middleware.

The only functionality that [`JsonDecoder`](https://github.com/relayphp/Relay.Middleware/tree/b4e09bd21e426732e009d91eb808ef5929af6633#jsondecoder) doesn't presently offer and that [`JsonContentHandler`](https://github.com/sparkphp/spark/blob/master/src/Handler/JsonContentHandler.php) does is checking for error conditions in JSON parsing.

Once the [related issue](https://github.com/relayphp/Relay.Middleware/issues/13) with [`JsonDecoder`](https://github.com/relayphp/Relay.Middleware/tree/b4e09bd21e426732e009d91eb808ef5929af6633#jsondecoder) has been resolved, we should consider using it and removing [`JsonContentHandler`](https://github.com/sparkphp/spark/blob/master/src/Handler/JsonContentHandler.php).

**Comment by shadowhand** [comment]
That's not entirely true, since `JsonContentHandler` works with types besides `application/json`.

**Comment by shadowhand** [comment]
I generally prefer our approach in ContentHandler because it makes it easier to write additional content-based middleware.

**Comment by elazar** [comment]
> That's not entirely true, since `JsonContentHandler` works with types besides `application/json`.

Fair point, though how often do we actually see `application/vnd.api+json` used?

> I generally prefer our approach in `ContentHandler` because it makes it easier to write additional content-based middleware.

Also a fair point. Maybe we should try to contribute it upstream to Relay?

**Comment by shadowhand** [comment]
@elazar we will (most likely) be using it extensively in the next version of WIW.

**Comment by elazar** [comment]
> Maybe we should try to contribute it upstream to Relay?

Thoughts?

**Comment by elazar** [comment]
Sounds like we're going to try to contribute our middleware to Relay rather than using theirs in Spark (see relayphp/Relay.Middleware#14). As such, closing this issue. If Relay accepts the contribution, we can open another PR to update the Relay version we're using and update our code to point to Relay's namespace instead of ours for the aforementioned middleware.
