### ISSUE TITLE
Replace Spark\Resolver\ResolverInterface with Relay\ResolverInterface

### ISSUE THREAD

**Issue by elazar** [sparkphp/spark#57]
[`Spark\Resolver\ResolverInterface`](https://github.com/sparkphp/spark/blob/master/src/Resolver/ResolverInterface.php) and [`Relay\ResolverInterface`](https://github.com/relayphp/Relay.Relay/blob/1.x/src/ResolverInterface.php) appear identical. Should we consider replacing usage of the former with the latter?

**Comment by shadowhand** [comment]
:+1:
