### ISSUE TITLE
ConfigurationSet class check can be static

### ISSUE THREAD

**Issue by shadowhand** [sparkphp/spark#59]
[This closure](https://github.com/sparkphp/spark/blob/master/src/Configuration/ConfigurationSet.php#L43) can have a `static` on it so that it persists between runs, since it doesn't `use` anything, the definition will never change.

**Comment by elazar** [comment]
Not sure there's much to be gained since, in the vast majority of cases, this code should only be executed once per request, but alright.

**Comment by shadowhand** [comment]
No longer valid.
