### ISSUE TITLE
Make it easier to add middleware to collection

### ISSUE THREAD

**Issue by shadowhand** [sparkphp/spark#79]
For instance, when using auth, it would be nice to be able to do this:

```php
$collection = $collection->withAddedMiddleware(AuthHandler::class, ActionHandler::class);
```

Where the signature is:

```php
function withAddedMiddleware(string $class, string $before = null) : static
```

**Comment by shadowhand** [comment]
@sparkphp/contributors what do you think about this?

**Comment by ameech** [comment]
I like it. I think `withAddedMiddleware` is a bit long, how about `withMiddleware`?

**Comment by shadowhand** [comment]
Well, the only problem is that I don't want to imply that the whole collection would be replaced. Though I guess in that scenario, you would just create a new collection instead of replacing the existing content.
